<a href="https://colab.research.google.com/github/19PA1A0205/Artificial-intelligence/blob/master/Numpy_Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Artificial Intelligence Tools, Techniques and Applications

 #Experiment No1:Numpy

 1) Different ways to create numpy arrays

In [ ]:
 
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
a = np.array([4,6,7])
a

array([4, 6, 7])

In [ ]:
 import numpy as np
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
 import numpy as np
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
 import numpy as np
a = np.linspace(10,20,num=5)
a

array([10. , 12.5, 15. , 17.5, 20. ])

 2)Add, remove, modify elements in an array

In [ ]:
 import numpy as np
q = np.arange(1,11)
a = np.insert(q,3,10)
a

array([ 1,  2,  3, 10,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
 import numpy as np
q = np.arange(1,19)
a = np.delete(q,3)
a

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
import numpy as np
e = np.array([1,2,3])
s = e*2
s

array([2, 4, 6])

In [ ]:
import numpy as np
s = np.arange(5)
q = np.append(s,10)
q

array([ 0,  1,  2,  3,  4, 10])

 3) Arithmetic operations on Numpy arrays

In [ ]:
import numpy as np
a = np.random.random((3,3))
b = np.random.random((3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.mod(a,b))
print(np.divide(a,b))
print(np.power(a,b))

[[0.6203225  1.28055132 0.54771677]
 [0.53350362 1.45644516 0.89797715]
 [1.86097397 0.71753887 0.81991482]]
[[ 0.0532909  -0.60194964 -0.48945614]
 [-0.4398091  -0.05016469  0.00566134]
 [-0.02195059  0.56273096 -0.34765054]]
[[0.09549002 0.31936708 0.01510659]
 [0.02279852 0.529679   0.20158273]
 [0.86568557 0.04954897 0.13784985]]
[[0.0532909  0.33930084 0.02913032]
 [0.04684726 0.70314023 0.00566134]
 [0.91951169 0.02090327 0.23613214]]
[[1.18796448 0.3604788  0.05617254]
 [0.09626354 0.93340719 1.01268909]
 [0.97668458 8.27005428 0.40448637]]
[[0.73452227 0.36154541 0.15981967]
 [0.22546546 0.76696571 0.70155187]
 [0.92403948 0.96606122 0.43058491]]


 4)Slicing and iterating of Numpy arrays

Slicing

In [ ]:
import numpy as np
a = np.arange(9)
s =a[1: 6]
 
s

array([1, 2, 3, 4, 5])

Iterating

In [ ]:
import numpy as np
 
arr = np.array([[1, 2, 3], [4, 5, 6]])
 
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
 import numpy as np
 
arr = np.array([1, 2, 3])
 
for x in arr:
  print(x)

1
2
3


 5)Matrix operations on Numpy arrays

In [ ]:
import numpy as np
b = np.array([[1,2],[4,5]])
c = np.array([[6,7],[7,9]])
print(np.add(b,c))
print(np.subtract(b,c))
print(np.multiply(b,c))
print (np.divide(b,c))

[[ 7  9]
 [11 14]]
[[-5 -5]
 [-3 -4]]
[[ 6 14]
 [28 45]]
[[0.16666667 0.28571429]
 [0.57142857 0.55555556]]
